prompt: italy
torch_device: cuda # cpu, cuda
vae: 
  name: AutoencoderKL
  module: diffusers
  pretrained_dir: runwayml/stable-diffusion-v1-5
  subfolder: vae
tokenizer:
  name: CLIPTokenizer #AutoTokenizer
  module: transformers
  pretrained_dir: runwayml/stable-diffusion-v1-5
  subfolder: tokenizer
text_encoder:
  name: CLIPTextModel
  module: transformers
  pretrained_dir: runwayml/stable-diffusion-v1-5
  subfolder: text_encoder
model:
  name: UNet2DConditionModel
  module: diffusers
  pretrained_dir: runwayml/stable-diffusion-v1-5
  subfolder: unet
scheduler:
  name: LMSDiscreteScheduler #UniPCMultistepScheduler #PNDMScheduler #LMSDiscreteScheduler #EulerDiscreteScheduler
  module: diffusers
  pretrained_dir: ./config/LMSDiscreteScheduler_config.json #runwayml/stable-diffusion-v1-5 #./config/LMSDiscreteScheduler_config.json #./config/EulerDiscreteScheduler_config
  subfolder: scheduler
params:
  seed: 1
  num_inference_steps: 55
  guidance_scale_min: 10
  guidance_scale_max: 10
  guidance_scale_random: False
  height: 512
  width: 512
  show_image: False
  #output_dir: location
  output_dirname_type: pipeline #generic
  save_denoising_iterations: False
  





